name = "Slit_sim"
uuid = "3e73f08a-dfd4-429d-b7be-66681dc9c62a"
authors = ["DaisukeKogure <kogure.d.816@ms.saitama-u.ac.jp>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
